FROM ubuntu:latest

RUN apt-get update

RUN apt-get -y install libmysqlclient-dev libssl-dev sysbench

ENV TYPE cpu
ENV THREADS 8
ENV TIME 10
ENV CPUMAXPRIMES 10000

RUN mkdir -p /var/result
VOLUME /var/result

COPY run.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/run.sh

ENTRYPOINT ["run.sh"]
CMD ["sysbench"]
