FROM ubuntu:latest

# build intial apk binary cache and install iperf
#RUN apk add --no-cache iperf \
#    && adduser -S iperf
RUN apt-get update
RUN apt-get -y install apt-utils iperf

# Expose the default iperf2 server port
EXPOSE 5001/tcp 5001/udp

# entrypoint allows you to pass your arguments to the container at runtime
# very similar to a binary you would run. For example, in the following
# docker run -it <IMAGE> --help' is like running 'iperf --help'
ENTRYPOINT ["iperf", "-w32K", "-s"]
